environment:
podcontroller:
  name: pod-controller
  namespace: icap-adaptation
  rolename: pod-controller-role
  saname: pod-controller-sa
  replicas: 1
  processimage: k8serviceaccount/go-k8s-process
  pod_count: 50
  process_pod_memory_limit: 1000Mi
  process_pod_memory_request: 300Mi
srv:
  name: srv
  replicas: 1
queue:
  adaptationRequest:
    hostname: "rabbitmq-service"
    port: "\"5672\""
minio:
  adaptationRequest:
    endpoint: "minio-server.minio.svc.cluster.local:9000"
    sourcebucket: "sourcefiles"
    processedbucket: "cleanfiles"
imagestore:
  podcontroller:
    registry: ""
    repository: k8serviceaccount/go-k8s-controller
    tag: v0.7.0
  srv:
    registry: ""
    repository: k8serviceaccount/go-k8s-srv
    tag: v0.5.0
  process:
    registry: ""
    repository: k8serviceaccount/go-k8s-process
    tag: v0.7.0
volumemountpath:
  source: "/var/source"
  target: "/var/target"
  transactions: /mnt/transactions
jaeger:
  host: "jaeger.jaeger.svc.cluster.local"
  port: "6831"
  on: "true"
